### ISSUE TITLE
Come up with a fulfillment process

### ISSUE THREAD

**Issue by mariacha** [thinkshout/pear#4]
## Tasks:
- [x] Research shipping options
- [x] Figure out what supplies would be needed (to ship)
- [x] Review shipping costs estimate
- [ ] Document a process for when and how to pull orders and fill them. Can put this in a google doc. Add the link to the Wiki Helpful Implementation links page. https://github.com/thinkshout/pear/wiki/Helpful-implementation-links

## This ticket is done when:
- [ ] There is documentation on the process of shipping shirts.

**Comment by khirsch** [comment]
We have two envelope options via USPS: 

1. https://tinyurl.com/okqcbft
2. http://tinyurl.com/zmkxwl2

Both envelope types are free via the carrier. The first option would allow us to fit multiple shirts into one envelope, but the second option will guarantee more consistent and straight-forward shipping costs, at least in my opinion.

**Comment by khirsch** [comment]
Flat rate price for a padded envelope is $7.20 - http://www.stamps.com/usps/priority-mail-flat-rate/

We should verify that a shirt will actually fit in an envelope of that size, though. The Tyvec envelope would cost roughly $6.65 to ship.

**Comment by khirsch** [comment]
https://docs.google.com/a/thinkshout.com/document/d/1fK2JRrOp19zAcW8SOpJI-FCQeIoiaK5R1pDWLnD_5R0/edit?usp=sharing
